In [ ]:
import numpy as np
array_2x2 = np.array([[1,2],[3,4]])
print(array)


[[1 2]
 [3 4]]


In [ ]:
array_random = np.random.rand(3, 4)

print(array_random)

[[0.22046242 0.20783578 0.22944246 0.68548462]
 [0.67182564 0.58512785 0.61026852 0.74106684]
 [0.19546151 0.0274571  0.74330729 0.35533138]]


In [ ]:
array_1=np.ones((3,3))
array_2=np.zeros((3,3))
print(array_1)
print(array_2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
array_random_6_3=np.random.rand(6,3)
trans_array_random_6_3=array_random_6_3.T
print(trans_array_random_6_3)

[[0.27940306 0.54678205 0.25366337 0.79739174 0.90898152 0.43824169]
 [0.36219731 0.01449019 0.15436059 0.07927707 0.10539342 0.880377  ]
 [0.16748831 0.02850938 0.48636261 0.80219301 0.16017771 0.01867974]]


In [ ]:
array_random_1=np.random.rand(1,2)
array_random_2=np.random.rand(2,3)
array_dot_product=np.dot(array_random_1,array_random_2)
print(array_dot_product)

[[0.92469121 0.54302844 0.99054773]]


In [40]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive
%cd git_repos


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive
/content/drive/MyDrive/git_repos


In [41]:
%cd data-science-toolkit/

/content/drive/MyDrive/git_repos/data-science-toolkit


In [15]:
!git config --global user.email "Yonickgt@gmail.com"
!git config --global user.name "Yonickgt"


In [44]:
!mv "../../Colab Notebooks/Tutorial 3.ipynb" "./"

mv: cannot stat '../../Colab Notebooks/Tutorial 3.ipynb': No such file or directory


In [23]:
!git add .
!git commit -m "Comment"


On branch main
Your branch is behind 'origin/main' by 5 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean


In [9]:
!git add "Tutorial\ 3.ipynb"

In [31]:
!git pull https://Yonickgt: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@github.com/Yonickgt/data-science-toolkit.git main

From https://github.com/Yonickgt/data-science-toolkit
 * branch            main       -> FETCH_HEAD
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.


In [32]:
! git config pull.rebase false

In [36]:
!git add .

In [37]:
!git commit -m "comment"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


In [38]:
!git push https://Yonickgt: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@github.com/Yonickgt/data-science-toolkit.git main --force

Everything up-to-date


In [34]:
!git status

On branch main
Your branch is behind 'origin/main' by 5 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

nothing to commit, working tree clean


In [22]:
!git switch main

Switched to branch 'main'
Your branch is behind 'origin/main' by 5 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)


In [21]:
!git restore "Tutorial 3.ipynb"

In [30]:
!git pull https://Yonickgt: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@github.com/Yonickgt/data-science-toolkit.git main


From https://github.com/Yonickgt/data-science-toolkit
 * branch            main       -> FETCH_HEAD
Already up to date.


In [35]:
!git pull

From https://github.com/Yonickgt/data-science-toolkit
 + 2a5b033...8eaf32e main       -> origin/main  (forced update)
Already up to date.


In [42]:
!git add "Tutorial 3.ipynb"

fatal: pathspec 'Tutorial 3.ipynb' did not match any files


In [43]:
!ls

python_basics.ipynb  README.md
